#!/bin/bash

# Make temporary dest dir, and clean up.
dest=$(mktemp -d)
trap "{ rm -rf $dest; rm -rf $binTemp; }" EXIT SIGINT SIGTERM

# Checkout src branch
git checkout src


# Build to temp directory
bundle exec jekyll build -qd $dest



# Checkout master, nuke everything
git checkout -f master
git rm -qr .
rm -rf *

# Copy in built files
cp -R $dest/* .

# Verify index.html exists
if [ ! -f index.html ]; then
    echo "index.html not found. ABORT!!!"
    exit 1
fi


git add .
git commit -m "Deploy to GitHub Pages"

git push

git checkout src
